                                        BASIC STATISTICS-2

Problem Statement : Hospital Patient Data Analysis

1.	Load the patient dataset

In [29]:
import pandas as pd
import numpy as np

billing=pd.read_csv("Billing_Data.csv")
billing

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [2]:
patient=pd.read_csv("Patient_Data.csv")
patient

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [3]:
patient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].

In [4]:
billing_col=['PatientID', 'Department', 'Doctor', 'BillAmount']
patient_billing_col=patient[billing_col]

In [5]:
patient_billing_col.head()

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN

3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].

In [13]:
drop_col=patient.drop(columns=['ReceptionistID', 'CheckInTime'],axis=1,inplace=True)
drop_col

In [14]:
patient

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

4.	Use groupby to find total bill amount per department.

In [16]:
total_bill=patient.groupby('Department')['BillAmount'].sum()
total_bill

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

5.	Remove duplicate patient records based on PatientID.

In [43]:
patient_dup=patient.drop_duplicates('PatientID')

In [44]:
patient_dup

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John      5925.0
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose      5925.0

6.	Fill missing BillAmount values with the mean bill amount

In [27]:
bill_amt_values=patient['BillAmount'].fillna(patient['BillAmount'].mean())
bill_amt_values

0    5000.0
1    5925.0
2    7500.0
3    6200.0
4    5925.0
5    5000.0
Name: BillAmount, dtype: float64

7.	Merge the billing dataset with patient dataset on PatientID.

In [34]:
merge_set=pd.merge(patient,billing,on="PatientID",how='inner')
merge_set

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,2000,3000
1,102,Bob,Neurology,Dr. John,5925.0,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,3000,3200
4,105,Eva,Dermatology,Dr. Rose,5925.0,1000,4000
5,101,Alice,Cardiology,Dr. Smith,5000.0,2000,3000

8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

In [58]:
newpatients = pd.DataFrame({
    'PatientID': [106, 107],
    'Name': ['Ram', 'Sam'],
    'Department': ['Dermatology', 'Cardiology'],
    'Doctor': ['Dr.Will', 'Dr.Fig'],
    'BillAmount': [6000, 7000],
    'InsuranceCovered': [3000, 2500],
    'FinalAmount': [3500, 4000]
})

concat_set=pd.concat([merge_set,newpatients],ignore_index=True)
concat_set

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,2000,3000
1,102,Bob,Neurology,Dr. John,5925.0,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,3000,3200
4,105,Eva,Dermatology,Dr. Rose,5925.0,1000,4000
5,101,Alice,Cardiology,Dr. Smith,5000.0,2000,3000
6,106,Ram,Dermatology,Dr.Will,6000.0,3000,3500
7,107,Sam,Cardiology,Dr.Fig,7000.0,2500,4000

9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [70]:
df = pd.DataFrame({
    'BillID': [101, 102, 103],
    'TotalAmount': [5000, 3000, 7000]
})
new_cols = pd.DataFrame({
    'InsuranceCovered': [2000, 1000, 3000],
    'FinalAmount': [3000, 2000, 4000]
})

df_final = pd.concat([df, new_cols], axis=1)

In [71]:
df_final

   BillID  TotalAmount  InsuranceCovered  FinalAmount
0     101         5000              2000         3000
1     102         3000              1000         2000
2     103         7000              3000         4000